version: "3"

services:
  flask_api:
    container_name: flask_api
    restart: always
    build: ./server
    ports:
      - "5000:5000"
    command: gunicorn -w 1 -b :5000 wsgi:app

  nginx:
    container_name: vue_ui
    restart: always
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - flask_api
